export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';
export const EDIT_TODO_ITEM = 'EDIT_TODO_ITEM';
export const CHECK_TODO_ITEM = 'CHECK_TODO_ITEM';
export const SELECT_TODO_ITEM = 'SELECTED_TODO_ITEM';
export const UNSELECT_TODO_ITEM = 'UNSELECTED_TODO_ITEM';
